### ISSUE TITLE
Turn Repo Examples Into Living Tests

### ISSUE THREAD

**Issue by alexfinnarn** [CivicActions/cypress-tests#3]
As discussed in #2, it is possible to move the code in examples to actual test files. The benefits of doing so include keeping test dependencies up-to-date and working together as well as making sure the advice in examples still works. 

I will list out items in a checklist that can be turned into issues, so this can be considered an epic.

- [x] #4
- [x] #7
- [x] #5
- [x] Add `axe-core` and `cypress-axe` for accessibility testing
- [x] #9
- [x] #19
- [x] #21
- [x] Modify the main project readme file to explain how to run and learn from the tests.
- [x] Add to readme how to submit issues relating to Cypress from project work. The goal would be to help everyone using Cypress to know about new techniques/solutions that come up in project work.

**Comment by dmundra** [comment]
The lists looks great. Looking forward to helping with this. We have working example of Cypress accessibility tests and github actions here https://github.com/CivicActions/accessibility that we can use.

**Comment by alexfinnarn** [comment]
Cool. I just made a PR and some issues linked to this epic. Have a look at those if you have some time, but I will pause now for some feedback.
