### ISSUE TITLE
Add Cypress as a dependency using Yarn

### ISSUE THREAD

**Issue by alexfinnarn** [CivicActions/cypress-tests#4]
Cypress needs to be added as a package. This will create the package.json file as well with some basic information. I usually leave the defaults so feel free to modify those as desired.

The biggest question I have is whether or not to put dependencies in the dev section or not. If this was a repo with an actual project being tested, then I think separating out the dev dependencies makes sense, but for a testing repository, you could argue that the testing dependencies are the main part of the project.

**Comment by dmundra** [comment]
Agreed with your second point that "testing dependencies are the main part of the project" so let's go with that for now. Left a comment on the PR about cypress version.
