### ISSUE TITLE
Add scripts and example tests

### ISSUE THREAD

**Issue by alexfinnarn** [CivicActions/cypress-tests#5]
I was thinking something like this:

```json
  "scripts": {
    "cy:run": "cypress run",
    "cy:open": "cypress open"
  },
```

And using the `cy:` prefix for Cypress-related commands. Thoughts?

**Comment by dmundra** [comment]
Works for me!

**Comment by alexfinnarn** [comment]
Sounds good. I will make a PR after #4 adds the initial package.json file.

**Comment by alexfinnarn** [comment]
@dmundra I added those scripts and the example tests Cypress adds when first booting up. I gotta say, I'm continually impressed with all their updates and even being able to start writing specs from the test runner, apparently.

I especially like the getting started example with all the code comments. I think that (or tests like it) can be great resources when onboarding people new to Cypress or just starting out at CivicActions.
