### ISSUE TITLE
Add Contribution Guide

### ISSUE THREAD

**Issue by alexfinnarn** [CivicActions/cypress-tests#7]
I usually use Gitflow, https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow, and `feature/[issue-number]` for branching. I don't think this repo needs to get fancy with workflows and hot fixing or any of that, but I think it makes sense to provide contributors guidance on how to create branches that can help link PRs to issues.

Acceptance Criteria:
- [x] Decide on how to create branches and link pull requests
- [x] Place notes in some kind of contributor documentation following https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by dmundra** [comment]
Ya we probably don't want to get overly strict either. I am fine with simple branch names, not requiring issues be created, and pull requests. We can add branch protection on main branch. I need to get admin access from @bobschmitt-civicactions to set that up.

I think the notes should go in `contributing.md` file (see https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors).

**Comment by alexfinnarn** [comment]
@dmundra I added a draft of a contribution guideline doc based on some things you wrote in this issue as well as my thoughts. To be honest, GitHub Copilot wrote a lot of the doc, lol, and gave a decent outline of the typical sections. 

Let me know what you think!

**Comment by dmundra** [comment]
@alexfinnarn looks great! 🚢 it.
