### ISSUE TITLE
Add Dependabot for keeping dependencies up-to-date

### ISSUE THREAD

**Issue by alexfinnarn** [CivicActions/cypress-tests#9]
Now that the initial Cypress dependency is merged in, it would be great to enable Dependabot to keep up-to-date with the latest Cypress and other dependency releases.

<img width="817" alt="Screen Shot 2022-12-06 at 10 50 13 AM" src="https://user-images.githubusercontent.com/3640707/205959103-162b0582-7e5e-447e-b5de-e317e3f6b8d3.png">

I think we can enable the bot in those settings and use a YAML file for config. 

Any thoughts on this? Do people approve of starting to change the settings to allow Depedabot updates? And maybe eventually this issue will have a PR with YAML file.

**Comment by dmundra** [comment]
Yes definitely allow Dependabot updates! With the branch policies turned on, Dependabot will create a PR whenever there are updates.

**Comment by alexfinnarn** [comment]
@dmundra I added a PR and set it to Wednesdays since that's when Drupal makes security notices...although the schedule might only apply to non-security updates, I'm not sure.

But I have gotten annoyed with daily Dependabot updates in the past so that's why I set it to weekly. Hopefully, it isn't too noisy for the posts to Slack, but we'll see once more packages are added.
